#!/usr/bin/env bash
@ ssh client configuration

Host *
PasswordAuthentication no
IdentifyFile ~/.ssh/school
SendEnv LANG LC_*
HashKnownHosts yes
GSSAPIAuthentication yes
GSSAPIDelegateCredentials no

